name: Deploy to Docker Hub

on:
  push:
    branches:
      - main
      - qa
      - test

jobs:
  docker-build-and-push:
    name: Build and Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    environment: DOCKER

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PW }}

      - name: Extract Docker image name
        id: meta
        run: |
          IMAGE_NAME=cyntax-org
          BRANCH_NAME=${GITHUB_REF##*/}
          echo "image=$IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "tag=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.tag }}
